name: CMake on Windows

on:
  push:
    branches: [ "omni" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Clone MSVC600 repository
      run: git clone https://github.com/itsmattkc/MSVC600.git

    - name: Set up VC98 environment
      shell: cmd
      run: |
        set VC98_PATH=${{ github.workspace }}\MSVC600\VC98
        call "%VC98_PATH%\Bin\VCVARS32.bat"
        set >> %GITHUB_ENV%
    
    - name: Configure CMake with vc6 preset
      shell: cmd
      run: |
        cmake --preset vc6
    
    - name: Build the project using nmake
      shell: cmd
      working-directory: ${{ github.workspace }}\build\vc6
      run: |
        nmake
